### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by azmeuk** [dsch/gsm0338#4]
Hi. First of all thank you for the project.

I had a feature idea, I would like to discuss it with you here before I submit you a pull request (of before you develop it, if you like it :))

I would love to have the ability to normalize characters that are not in the gsm0338 table (if they can be normalized), using [unicodedata.normalize](https://docs.python.org/3.6/library/unicodedata.html), instead of deleting them for instance.

I though of two ways of doing this:

- Having the `errors` from the `encoding` method have the possible values ‘NFC’, ‘NFKC’, ‘NFD’, and ‘NFKD’. The behavior would be to normalize non gsm03.38 characters before either deleting them, replacing them with `?` or raising an exception.
- Having an additional `normalize` parameter to the `encoding` method.

Currently I do this myself, but I either must maintain a regex containing the whole gsm03.38 table. I think it would be better if this library does that job.

What do you think?

**Comment by dsch** [comment]
Hi
Nice to hear, that the module is in use. Normalizing characters as an error handler (instead of `'ignore'` or `'replace'` seams for me a reasonable extension of the existing functionality.

The module tries to implement the codecs.Codec class. So extending the interface of the `encoding` method is in my opinion no option.
Although using the `error` parameter to define different error handling seams appropriate.
Therefore new error handles should be registered with `codecs.register_error` during module importing. But I didn't yet fully understand how to use `codecs.register_error` and `codecs.lookup_error`. Perhaps the existing handling is not as intended by the codecs module.

A pull request would be in any case highly welcome.

**Comment by simanto604newscred** [comment]
Hi @azmeuk,

Do you have any further update on this? It would be great to have, thanks.

**Comment by dsch** [comment]
Hallo all
I just refactored the module to use the build-in error handles as described in PEP 293. This should make is much easier to implement and register your own error handler.
Perhaps I can provide an example, but I didn't understand where a normalized character could ratter be encoded then the original one. Can you provide some examples?

**Comment by azmeuk** [comment]
@simanto604newscred I did not take time to tackle this yet.
@dsch Thank you for the refactoring.

Here is how I currently do this:

```python
import re
import unicodedata
import gsm0338

NOT_GSM_CHAR_PATTERN = r'[^ \n@£$¥èéùìòÇØøÅåΔ_ΦΓΛΩΠΨΣΘΞ^{}\\[~\]|€ÆæßÉ!"#¤%&\'()*+,-./0-9:;<=>?¡A-ZÄÖÑÜ§¿a-zäöñüà]'
NOT_GSM_CHAR_REGEXP = re.compile(NOT_GSM_CHAR_PATTERN)

def ucs2_char_replace(matchobj):
    normalized = unicodedata.normalize('NFKD', matchobj.group(0))
    return normalized.encode('gsm03.38', 'ignore').decode("gsm03.38")

def ucs2_to_gsm_encoding(ucs2_message):
    return NOT_GSM_CHAR_REGEXP.sub(ucs2_char_replace, ucs2_message)

assert ucs2_to_gsm_encoding("êëçîï→") == "eecii"
```
